### ISSUE TITLE
Include Argentinean DNI

### ISSUE THREAD

**Issue by joelibaceta** [ronzalo/id_number_latam#2]
Documents in Argentina have the following format:

**11.111.111**

But they don't have a verification digit

**Comment by joelibaceta** [comment]
Pull request proposed #1

**Comment by JeremasPosta** [comment]
I think that we can't validate DNI, but yes Cuil and Cuit.

**Comment by ronzalo** [comment]
Merged https://github.com/ronzalo/id_number_latam/pull/1
